### ISSUE TITLE
onnx version？

### ISSUE THREAD

**Issue by Amorter** [86maid/ddddocr#12]
![J3 $D{~5~_ERYP@ $@QI4K2](https://github.com/86maid/ddddocr/assets/63935225/86dfd0a9-7b8c-4915-81d5-b57f77878bae)
![image](https://github.com/86maid/ddddocr/assets/63935225/b1a5c3c9-804c-4234-b8c9-c378eec982f2)
看起来像是onnx的报错，大佬有头绪吗？

**Comment by Amorter** [comment]
我写了一个用于识别验证码的rust库，通过pyo3实现了python语言绑定，所以会有python相关报错，不过看最主要的报错好像是onnx那个

**Comment by 86maid** [comment]
那就换版本试试












xchuang233
***@***.***


---Original---
From: ***@***.***&gt;
Date: Sun, Jun 16, 2024 15:15 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [86maid/ddddocr] onnx version？ (Issue #12)




 
我写了一个用于识别验证码的rust库，通过pyo3实现了python语言绑定，所以会有python相关报错，不过看最主要的报错好像是onnx那个

**Comment by Amorter** [comment]
> 那就换版本试试 xchuang233 ***@***.***
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, Jun 16, 2024 15:15 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: Re: [86maid/ddddocr] onnx version？ (Issue #12) 我写了一个用于识别验证码的rust库，通过pyo3实现了python语言绑定，所以会有python相关报错，不过看最主要的报错好像是onnx那个 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

这里的版本是在哪里更换的呢，主要是不太明白这个【8】和1....7是哪里来的，这个应该不是指onnx crate的版本吧

**Comment by 86maid** [comment]
布吉岛








xchuang233
***@***.***


---Original---
From: ***@***.***&gt;
Date: Sun, Jun 16, 2024 15:25 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [86maid/ddddocr] onnx version？ (Issue #12)




  
那就换版本试试 xchuang233 @.***
 …
 ---Original--- From: @.&gt; Date: Sun, Jun 16, 2024 15:15 PM To: @.&gt;; Cc: @.&gt;; Subject: Re: [86maid/ddddocr] onnx version？ (Issue #12) 我写了一个用于识别验证码的rust库，通过pyo3实现了python语言绑定，所以会有python相关报错，不过看最主要的报错好像是onnx那个 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
这里的版本是在哪里更换的呢，主要是不太明白这个【8】和1....7是哪里来的，这个应该不是指onnx crate的版本吧
